force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>Saves information related to the comments of the movies made by users.</description>
    <label>Review</label>
    <nameField>
        <displayFormat>R-OMDb-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>CreatedDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/MovieId__c.field-meta.xml
<CustomField>
    <fullName>MovieId__c</fullName>
    <description>Id from OMDb API</description>
    <externalId>true</externalId>
    <label>Movie Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Repository/ReviewRepository.cls
public class ReviewRepository {
    
    public ReviewRepository(){}
    
    public static List<Review__c> getReviewsByMovieId(String movieId){
        return [SELECT Id, Name, Author__c, Qualification__c, Comment__c, CreatedDate__c
				FROM Review__c
                WHERE MovieId__c = :movieId
                ORDER BY CreatedDate__c DESC];
    }

    public static List<Review__c> getAllReviews(){
        return [SELECT MovieId__c, Id, Name, Author__c, Qualification__c, Comment__c, CreatedDate__c
                FROM Review__c
                ORDER BY CreatedDate__c DESC];
    }

    public static Id insertReview(String movieId, String authorName, String comment,
                                    Integer qualification){
        Review__c review = new Review__c(
                            MovieId__c = movieId,
                            Author__c = authorName,
                            Comment__c = comment,
                            Qualification__c = qualification);
        insert review;        
        return review.Id;                                                    
    }
}