force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <description>Saves information related to the comments of the movies made by users.</description>
    <label>Review</label>
    <nameField>
        <displayFormat>R-OMDb-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/MovieId__c.field-meta.xml
<CustomField>
    <fullName>MovieId__c</fullName>
    <description>Id from OMDb API</description>
    <externalId>true</externalId>
    <label>Movie Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Service/ReviewService.cls
public class ReviewService {
    
    private static final String ANONYMOUS_DEFAULT_AUTHOR_NAME  = 'Anonymous';
    
    private ErrorHandler errorHandler;

    public ReviewService(ErrorHandler errorHandler){
        this.errorHandler = errorHandler;
    }
    
    public static ID createReview(String movieId, String authorName, String comment,
        						  Integer qualification){
		Movie movieRelated = MovieOMDbAPIService.getMovieById(movieId);
		if(!errorHandler.hasErrorReviewException(authorName, comment, qualification)){
            Review__c review = new Review__c(
                                MovieId__c = movieId,
                                Author__c=emptyAuthorNameToAnonymus(authorName),
                                Comment__c=comment,
                                Qualification__c=qualification);
            insert review;        
            return review.Id;            
        }                                      
 		return null;                                     
    }

    public static Movie getMoviesWithReviewsByMovieId(String movieId){
        Movie movie = MovieOMDbAPIService.getMovieById(movieId);
        movie.reviews = ReviewRepository.getReviewsByMovieId(movieId);
        return movie;
    }

    public static List<Movie> getMoviesWithReviewsByMovieTitle(String movieTitle){
        List<Review__c> movieReviews = new List<Review__c>();
        List<Movie> movies = MovieOMDbAPIService.getMoviesByTitle(movieTitle);

        for(Movie movie: movies){
            movieReviews = ReviewRepository.getReviewsByMovieId(movie.imdbID);
            movie.reviews = movieReviews; 
        }
        return movies;
    }
    
    private static String emptyAuthorNameToAnonymus(String authorName){
        if(String.isBlank(authorName)){
            authorName = ANONYMOUS_DEFAULT_AUTHOR_NAME;
        }
        return authorName;
    }

}